# Generated by Django 5.1.1 on 2024-10-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('event_link', models.URLField(blank=True, max_length=128, verbose_name='Ссылка на событие')),
                ('receiver_id', models.UUIDField(db_index=True, editable=False, verbose_name='ID получателя')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ('-time_create',),
            },
        ),
    ]
